#17 exibir app version
AriReboucas/buscador-cep pull request #20
Opened 2024-04-26 19:11 UTC by AriReboucas

- Inclusão do footer para apresentar dados de versão e desenvolvedor
- Importação da versão do package.json para o footer

2024-04-26 21:29 UTC, tiloreboucas commented
> - Inclusão do footer para apresentar dados de versão e desenvolvedor
> - Importação da versão do package.json para o footer

Falta print para evidênciar funcionamento da implementação

2024-04-26 21:34 UTC, tiloreboucas requested changes

2024-04-26 21:34 UTC, tiloreboucas commented on src/App.js
> +        <p>Desenvolvido por: Ari Rebouças</p>
Falta link de contato do dev, email ou redes sociais

2024-04-26 22:43 UTC, AriReboucas commented
mobile:
![image](https://github.com/AriReboucas/buscador-cep/assets/146797507/29201a4c-5c9b-4d60-ab1d-ee568e1a81a8)

desktop:
![image](https://github.com/AriReboucas/buscador-cep/assets/146797507/aca319c3-fda9-4cb2-9e21-7a87e1d9008b)

2024-04-26 23:17 UTC, tiloreboucas requested changes

2024-04-26 23:17 UTC, tiloreboucas commented on src/App.js
> +          <a className="dev" href="https://github.com/AriReboucas">
Links externos devem sempre abrir em uma nova janela para não perderem a referencia

2024-04-29 18:28 UTC, tiloreboucas approved these changes

2024-04-29 18:30 UTC, merged